### ISSUE TITLE
Switch default branch to main 

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCommunity/zulip-archive#1]
Thank you!

**Comment by SaschaMann** [comment]
Unfortunately this breaks the zulip-archive tool because it has `master` hardcoded. That's also the reason why it's 404ing. I had it as `main` at first but then had to switch back.

**Comment by SaschaMann** [comment]
There's an open PR to add support for it but it's not yet merged: https://github.com/zulip/zulip-archive/pull/48

**Comment by logankilpatrick** [comment]
My bad, feel free to switch back. What can we do to update the tool?

**Comment by SaschaMann** [comment]
I don't feel like maintaining a fork with manually applied patches, so we can just wait for the PR to be merged, I think.

**Comment by rht** [comment]
The PR has been merged.

**Comment by rht** [comment]
Was referring to https://github.com/zulip/zulip-archive/pull/48

**Comment by logankilpatrick** [comment]
Thanks!
