### ISSUE TITLE
Make the Zulip Archive indexed by Google

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaCommunity/zulip-archive#3]
Based on my searches, the archive is not getting indexed well, I can search the exact text and not see the result. What can we do to improve this?

**Comment by rht** [comment]
https://github.com/zulip/zulip-archive/pull/66 has been merged. @SaschaMann do you want to test deploy? It should look like this: https://github.com/rht/zulip-archive-sample/blob/main/stream/274208-helpdesk-(published)/topic/.2E.2E.2E.2Etesting.20leading.20dots.html. Though there is https://github.com/zulip/zulip-archive/issues/63 not yet fixed, but search engine indexability outweighs the custom css feature I think?

**Comment by rht** [comment]
Rendered: https://rht.github.io/zulip-archive-sample/.

**Comment by SaschaMann** [comment]
> Though there is zulip/zulip-archive#63 not yet fixed, but search engine indexability outweighs the custom css feature I think?

Yes, I think so. I'll update this repo later today.

**Comment by SaschaMann** [comment]
Done, seems to work: https://juliacommunity.github.io/zulip-archive/

Getting the CSS and meta-tags back would be really nice but I think this is worth it.
