### ISSUE TITLE
The repo still contains Jekyll-specific files

### ISSUE THREAD

**Issue by rht** [JuliaCommunity/zulip-archive#4]
There are still the old Jekyll-generated pages (e.g. https://github.com/JuliaCommunity/zulip-archive/blob/master/274208-helpdesk-(published)/topic/.2E.2E.2E.2Etesting.20leading.20dots.html -- notice the Jekyll metadata and that the title is still "Zulip Chat Archive" only) that are automatically copied by the Action script, and could be removed.

**Comment by SaschaMann** [comment]
Is there an easy way to fix this other than resetting the repo and having it rebuild the archive from scratch?

**Comment by rht** [comment]
You can do a commit to delete that folder (make sure not to delete the wrong folder), and the subsequent single commits by GH Action won't contain the folder. But it's not just that folder that needs to be deleted. There are several other Jekyll-specific files as well. Let me make the list.

**Comment by rht** [comment]
To delete:
- 274208-helpdesk-(published)
- _layouts
- index.md

The stream/274208-helpdesk-(published) folder is for the new non-Jekyll version.

**Comment by rht** [comment]
You can look at https://github.com/rht/zulip-archive-sample to double-check.

**Comment by SaschaMann** [comment]
Done, thanks :)
